syntax = "proto3";

import "brightness.proto";
import "power.proto";
import "audio.proto";
import "wifi.proto";
import "update.proto";
import "frame.proto";

package BSB_State;

message State {
    optional string device_name = 1;

    optional BSB_State.Power power = 2;

    optional BSB_State.Brightness brightness = 3;

    optional BSB_State.AudioVolume audio_volume = 4;

    optional BSB_State.Wifi wifi = 5;

    optional BSB_State.Update update = 6;

    optional BSB_Frame.Frame frame = 7;
}
