syntax = "proto3";

import "brightness.proto";
import "power.proto";
import "audio.proto";
import "wifi.proto";
import "update.proto";
import "frame.proto";

package BSB_State;

message StateUpdate {
    oneof state {
        string device_name = 1;

        BSB_State.Power power = 2;

        BSB_State.Brightness brightness = 3;

        BSB_State.AudioVolume audio_volume = 4;

        BSB_State.Wifi wifi = 5;

        BSB_State.Update update = 6;

        BSB_Frame.Frame frame = 7;
    }
}

message State {
    fixed64 timestamp = 1;

    repeated StateUpdate updates = 2;
}
