syntax = "proto3";

package BSB_State;

enum WifiConnectionStatus {
    CONNECTED = 0;
    CONNECTING = 1;
    DISCONNECTING = 2;
    RECONNECTING = 3;
}

enum WifiSecurity {
    UNKNOWN = 0;
    OPEN = 1;
    WPA = 2;
    WPA2 = 3;
    WEP = 4;
    WPA_WPA2 = 5;
    WPA3 = 6;
    WPA2_WPA3 = 7;
}

enum IpConfigurationMethod {
    DHCP = 0;
    STATIC = 1;
}

message WifiStateUnknown {
}

message WifiStateDisconnected {
}

message WifiStateConnected {
    WifiConnectionStatus status = 1;
    string ssid = 2;
    string bssid = 3;
    uint32 channel = 4;
    uint32 rssi = 5;
    WifiSecurity security = 6;
}

message IpAddress {
    IpConfigurationMethod method = 1;
    string address = 2;
    string gateway = 3;
    string netmask = 4;
}

message Wifi {
    oneof wifi_state {
        WifiStateUnknown unknown = 1;
        WifiStateDisconnected disconnected = 2;
        WifiStateConnected connected = 3;
    }

    optional IpAddress ipv4_address = 4;
    optional IpAddress ipv6_address = 5;
}
